### ISSUE TITLE
애플리케이션 개발에 사용할 언어?

### ISSUE THREAD

**Issue by Junsang-Mun** [alcoholcoders/whoosh#2]
개발을 시작하지 그런데

# 이슈 제목
무슨 언어를 사용해야 하는가

# 이슈의 목적
개발 언어 선정

# 이슈 해결 방법
- 애플리케이션 개발 단계 학습
- 언어 종류 리스트업
- 크로스플랫폼/네이티브 선택
- 등...

**Comment by Junsang-Mun** [comment]
근데 iOS랑 Android 둘이 너무 추구하는 UX UI가 달라서 처음 앱 개발해보는 사람들에게는 오히려 Cross-platform으로 개발하는게 독이 될수도 있지 싶어요

**Comment by windowdong11** [comment]
그러면 다들 아이폰 있으니까 IOS로 개발하는건 어떨까요?
UI도 깔끔한 것 같아서 디자인 관련해서 조금 손 쓸 부분이 줄어들지 않을까 싶어요

**Comment by Junsang-Mun** [comment]
@ryuhajin 아이폰 썼었어요????

**Comment by ryuhajin** [comment]
> @ryuhajin 아이폰 썼었어요????

넹 저 아이폰 12 pro! iOS 좋아욘

**Comment by Junsang-Mun** [comment]
<img width="69" alt="image" src="https://user-images.githubusercontent.com/99532497/191289230-f979bafc-859f-479f-9405-a8f66e3af9fa.png">
Swift 가실까요?

**Comment by ryuhajin** [comment]
> <img alt="image" width="69" src="https://user-images.githubusercontent.com/99532497/191289230-f979bafc-859f-479f-9405-a8f66e3af9fa.png">
> 
> Swift 가실까요?

Xcode 감당 가능 ? (참고로 잠깐 써봤는데 한국어 자료 별로 없음...)

**Comment by Junsang-Mun** [comment]
> Xcode 감당 가능 ? (참고로 잠깐 써봤는데 한국어 자료 별로 없음...)

솔직히 Xcode... 좀 많이 별로긴 한데
iOS만 네이티브로 할거면 그게 가장 속편하지 않을까요.

아니면 Flutter이나 RN으로 iOS쪽만 디벨롭하는 방법도 있긴 합니다만

**Comment by Hweeba** [comment]
Swift, Xcode Flutter 공부....ㄷㄷ 고민해주셔서 감사합니다.! 잘따르고 배워갈게요!

**Comment by ryuhajin** [comment]
그럼 일단 iOS 확정 // 스위프트로 고?

**Comment by Junsang-Mun** [comment]
그럴까요? Swift 고?

**Comment by Junsang-Mun** [comment]
우선 **iOS** 기반으로 **Swift**를 사용하는 걸로 하고 이슈 닫겠습니다!
