### ISSUE TITLE
첫 세션에서 무슨 얘기 할지 어젠다 정리

### ISSUE THREAD

**Issue by Junsang-Mun** [alcoholcoders/whoosh#4]

**Comment by windowdong11** [comment]
이번 주에 개발할 기능?

**Comment by Junsang-Mun** [comment]
개발할 기능부터 얘기할 수 있으려나...
애플리케이션 구조부터 만들고 시작하지 않을까요

**Comment by windowdong11** [comment]
간단하게 피그마 같은걸로 그리고 하면 괜찮지 않을까 싶었는데
생각해보니 그리고 수정하고(기능 넣고 빼고) 하는 것도 꽤 걸릴 것 같기도 해요

**Comment by Junsang-Mun** [comment]
그럼 스프린트 1에서는 프로토타이핑으로 끝내는것도 나쁘지 않을 것 같아요

**Comment by Hweeba** [comment]
1차 회의록 : https://jamboard.google.com/d/1QjqUHYHN7vDyPbU2Nuj7zaQRzthqrsWg8Gn8j89MJY0/viewer?userstoinvite=eyesibar21%40gmail.com&ts=6343705e&actionButton=1&f=0

**Comment by Junsang-Mun** [comment]
세션 종료. 이슈 닫겠습니다 :)
